### ISSUE TITLE
Training On less than 150 num_classes, triggers Cuda error

### ISSUE THREAD

**Issue by AhmadZobairSurosh** [NVlabs/SegFormer#92]
Hi
I am training on my custom dataset with the almost the  same configs and parameters as ade20k_repeat with little change to match my dataset.
I have only 4 classes on my class_names.py (my_dataset_classes() and my_dataset-palette() ), but if set num_classes to any number less than 150,  in segformer.b1.512x.512.my-dataset.40k.py, it triggers the following cuda error. 

Potential cause: ( I am training on 2 Gpus, but once the training starts, only 1 Gpu will be used). 
command for training: ./tools/dist_train.sh local_configs/segformer/B4/segformer.b4.512x512.my-dataset.40k.py 1

```
2022-07-13 09:49:01,708 - mmseg - INFO - Loaded 40310 images
2022-07-13 09:49:03,218 - mmseg - INFO - Loaded 2980 images
2022-07-13 09:49:03,219 - mmseg - INFO - Start running, host: zobair@zobair, work_dir: /mnt/sdc/zobair/dataset/segformer/SegFormer/work_dirs/segformer.b4.512x512.my-dataset.40k
2022-07-13 09:49:03,219 - mmseg - INFO - workflow: [('train', 1)], max: 40000 iters
Traceback (most recent call last):
  File "./tools/train.py", line 166, in <module>
    main()
  File "./tools/train.py", line 162, in main
    meta=meta)
  File "/mnt/sdc/zobair/floor-plans/segformer/SegFormer/mmseg/apis/train.py", line 115, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/server/anaconda3/envs/for-test1/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 131, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/server/anaconda3/envs/for-test1/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/server/anaconda3/envs/for-test1/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 46, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/mnt/sdc/zobair/floor-plans/segformer/SegFormer/mmseg/models/segmentors/base.py", line 153, in train_step
    loss, log_vars = self._parse_losses(losses)
  File "/mnt/sdc/zobair/floor-plans/segformer/SegFormer/mmseg/models/segmentors/base.py", line 204, in _parse_losses
    log_vars[loss_name] = loss_value.item()
RuntimeError: CUDA error: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /opt/conda/conda-bld/pytorch_1595629403081/work/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x4d (0x7f92c8b1e77d in /home/server/anaconda3/envs/for-test1/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xb5d (0x7f92c8d6ed9d in /home/server/anaconda3/envs/for-test1/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f92c8b0ab1d in /home/server/anaconda3/envs/for-test1/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x53f0ea (0x7f93023a10ea in /home/server/anaconda3/envs/for-test1/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x1817da (0x55db2fde37da in /home/server/anaconda3/envs/for-test1/bin/python)
frame #5: <unknown function> + 0xfa2d8 (0x55db2fd5c2d8 in /home/server/anaconda3/envs/for-test1/bin/python)
frame #6: <unknown function> + 0xfad68 (0x55db2fd5cd68 in /home/server/anaconda3/envs/for-test1/bin/python)
frame #7: <unknown function> + 0xfad7c (0x55db2fd5cd7c in /home/server/anaconda3/envs/for-test1/bin/python)
frame #8: <unknown function> + 0xfad7c (0x55db2fd5cd7c in /home/server/anaconda3/envs/for-test1/bin/python)
frame #9: <unknown function> + 0xfad7c (0x55db2fd5cd7c in /home/server/anaconda3/envs/for-test1/bin/python)
frame #10: <unknown function> + 0xfad7c (0x55db2fd5cd7c in /home/server/anaconda3/envs/for-test1/bin/python)
frame #11: <unknown function> + 0xfad7c (0x55db2fd5cd7c in /home/server/anaconda3/envs/for-test1/bin/python)
frame #12: <unknown function> + 0xfad7c (0x55db2fd5cd7c in /home/server/anaconda3/envs/for-test1/bin/python)
frame #13: <unknown function> + 0xfad7c (0x55db2fd5cd7c in /home/server/anaconda3/envs/for-test1/bin/python)
frame #14: <unknown function> + 0x12b327 (0x55db2fd8d327 in /home/server/anaconda3/envs/for-test1/bin/python)
frame #15: PyDict_SetItemString + 0x89 (0x55db2fd99e59 in /home/server/anaconda3/envs/for-test1/bin/python)
frame #16: PyImport_Cleanup + 0xab (0x55db2fe0ed0b in /home/server/anaconda3/envs/for-test1/bin/python)
frame #17: Py_FinalizeEx + 0x64 (0x55db2fe83304 in /home/server/anaconda3/envs/for-test1/bin/python)
frame #18: <unknown function> + 0x232960 (0x55db2fe94960 in /home/server/anaconda3/envs/for-test1/bin/python)
frame #19: _Py_UnixMain + 0x3c (0x55db2fe94ccc in /home/server/anaconda3/envs/for-test1/bin/python)
frame #20: __libc_start_main + 0xf3 (0x7f93265a70b3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #21: <unknown function> + 0x1d7555 (0x55db2fe39555 in /home/server/anaconda3/envs/for-test1/bin/python)

Traceback (most recent call last):
  File "/home/server/anaconda3/envs/for-test1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/server/anaconda3/envs/for-test1/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/server/anaconda3/envs/for-test1/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/server/anaconda3/envs/for-test1/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/server/anaconda3/envs/for-test1/bin/python', '-u', './tools/train.py', '--local_rank=0', 'local_configs/segformer/B4/segformer.b4.512x512.fp.40k_single-gpu.py', '--launcher', 'pytorch']' died with <Signals.SIGABRT: 6>.
```

**Comment by AhmadZobairSurosh** [comment]
Hi. 
I have found the issue. apparently in mmsegment, your labels(masks) should be in range of [0,n-1] where n is the num_of_classes. 

I had four classes and now my masks are between [0-3]. I can train on 4 classes now and the problem is solved. I am closing this issue!
